### ISSUE TITLE
X and Y axis not behaving as expected

### ISSUE THREAD

**Issue by MarcGamesons** [AkkaWakka/MouseBits#2]
When I tried your mod ingame and activated the X axis (horizontal) I could only place objects on the Y axis (vertical) is that intended or a bug?

In your mod the Y axis is horizontal and X axis is vertical.

Shouldn't it be like this [image](https://www.3dcontentcentral.com/ShowModels/ContentCentral/___Blocks___/X-Y%20Origin%20-%201d794fa8-2900-4974-b170-f6cd29ce6fe0/Files/X-Y%20Origin.SLDBLK.jpg)  for example.

A simple rename of the limitX and limitY variable would fix this like I did in the attached file.
[mousebits.lua - fix.zip](https://github.com/AkkaWakka/MouseBits/files/846527/mousebits.lua.-.fix.zip)

Oh and by the way great mod I love it.

**Comment by AkkaWakka** [comment]
I've swapped them over, as part of a general rename/refactor.  I'd named things one way and was thinking about them another.

Thanks for the bug report; I'm glad you like the mod.
